# -*- coding: utf-8 -*-
"""stock_price_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYiej6RoQLUTqrFtWOOS5EB6O9vAnSgz

# Import necessary lib
"""

import numpy as np
import pandas as pd
import warnings
from scipy.stats import randint

# Scikit-learn: preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Scikit-learn: models
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sklearn.neighbors import KNeighborsRegressor

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

warnings.filterwarnings("ignore")

"""### Task 1: Data Loading"""

df = pd.read_csv('stock_data.csv')
df.head(3)

from ydata_profiling import ProfileReport
profile = ProfileReport(df, title="Stock Data Profiling Report")

# Display the profiling report
profile.to_file("stock_data_profiling_report.html")

"""### Task 2: Data Preprocessing"""

# 1. Drop 'Unnamed: 0' if it exists
df = df.drop(columns=['Unnamed: 0'], errors='ignore')

# 2. Separate features (X) and target (y)
X = df.drop('Stock_2', axis=1)
y = df['Stock_2']

# 3. Identify numerical columns
numeric_features = X.select_dtypes(include=np.number).columns.tolist()

# 4. Numeric pipeline: impute missing values + scale
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# 5. ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_pipeline, numeric_features)
    ],
    remainder='drop'  # drop non-numeric columns if any
)

print("Preprocessor ready with numeric features:", numeric_features)

"""### Task 3: Pipeline Creation"""

# numeric pipeline
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_pipeline, numeric_features)
    ]
)

# KNN model
knn = KNeighborsRegressor(n_neighbors=50)

# full pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', knn)
])

"""### Data Splitting"""

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""### Task 5: Model Training"""

pipeline.fit(X_train, y_train)

"""### Task 6: Cross-Validation"""

cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='neg_mean_squared_error')
cv_rmse = np.sqrt(-cv_scores)
print(f"RMSE: {cv_rmse}")
mean_rmse = np.mean(cv_rmse)
print(f"\nAverage RMSE : {mean_rmse:.4f}")
std_rmse = np.std(cv_rmse)
print(f"Standard deviation : {std_rmse:.4f}")

"""### Task 7: Hyperparameter Tuning"""

# Build pipeline
knn_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', KNeighborsRegressor())
])

# Parameter distributions
param_dist = {
    'model__n_neighbors': randint(5, 100),
    'model__weights': ['uniform', 'distance'],
    'model__p': [1, 2]   # Manhattan vs Euclidean
}

# Randomized Search
random_search = RandomizedSearchCV(
    estimator=knn_pipe,
    param_distributions=param_dist,
    n_iter=50,
    cv=5,
    scoring='r2',
    n_jobs=-1,
    verbose=2,
    random_state=42
)

# Fit
random_search.fit(X_train, y_train)

# Best parameters
print("Best KNN Params:", random_search.best_params_)
print("Best CV R2 Score:", random_search.best_score_)

# Evaluate on test set
y_pred = random_search.predict(X_test)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print(f"R2 Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE: {mae:.4f}")

"""### Task 8,9: Best Model Selection &  Model Performance Evaluation"""

# Get the best pipeline from RandomizedSearchCV
best_model_pipeline = random_search.best_estimator_

# Predict on test set
y_pred_best_model = best_model_pipeline.predict(X_test)

# Evaluate
r2_best_model = r2_score(y_test, y_pred_best_model)
rmse_best_model = np.sqrt(mean_squared_error(y_test, y_pred_best_model))
mae_best_model = mean_absolute_error(y_test, y_pred_best_model)

# Print results
print("\n--- Best Model Performance on Test Set ---")
print("Best Params:", random_search.best_params_)
print(f"R2 Score: {r2_best_model:.4f}")
print(f"RMSE: {rmse_best_model:.4f}")
print(f"MAE: {mae_best_model:.4f}")

"""### Task 10: Save the Model Pipeline"""
import pickle
with open("stockPrice_knn_pipeline.pkl", "wb") as f:
    pickle.dump(best_model_pipeline, f)

print("✅ KNN pipeline saved as stockPrice_knn_pipeline.pkl")